#!/bin/sh
python manage.py collectstatic
sudo service uwsgi restart
sudo service nginx restart
sudo service redis-server restart
sudo redis-cli FLUSHALL
#python manage.py celeryd_detach
#python manage.py warmcache
