#!/bin/sh
python manage.py collectstatic
python manage.py compilemessages
service uwsgi restart
service nginx restart
service redis-server restart
redis-cli FLUSHALL
#python manage.py celeryd_detach
#python manage.py warmcache
